src/main/java/com/awsexam/entity/Question.java
package com.awsexam.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
 
@Entity
@Table(name = "QUESTIONS")
public class Question implements Serializable {
 
   	private static final long serialVersionUID = -5925792767165839407L;
   	
	private int quenumber;
	private String que;
	private String ans;
   
    @Id
    @Column(name = "quenumber", nullable = false)
    public int getQueNumber() {
		return quenumber;
	}

	public void setQueNumber(int quenumber) {
		this.quenumber = quenumber;
	}
    
	@Column(name = "que", nullable = false,length = 500)
	public String getQue() {
		return que;
	}

	public void setQue(String que) {
		this.que = que;
	}

	@Column(name = "ans", nullable = false)
	public String getAns() {
		return ans;
	}

	public void setAns(String ans) {
		this.ans = ans;
	}
}

src/main/java/com/awsexam/model/Login.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.awsexam.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class Login {
	@NotNull(message = "Please enter your userid")
	@Size(min=4,max=15 , message = "User Id must be between 4 and 15 characters")
    private String userName;
	
	@NotNull(message = "Please enter your password.")
	@Size(min=8,max=15 , message = "Password must be between 8 and 15 characters")
    
	private String password;   

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}

src/main/java/com/awsexam/controller/LoginController.java
package com.awsexam.controller;

import java.util.Enumeration;
import java.util.Optional;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.core.env.Environment;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;

import com.awsexam.entity.UserEntity;
import com.awsexam.model.Login;
import com.awsexam.security.SecurityService;
import com.awsexam.service.LoginService;
import com.awsexam.service.QuestionService;
import com.awsexam.utility.Utils;

@Controller
@SessionAttributes({"userName","userId"})
public class LoginController {
	
	@Lazy
	@Autowired
    private PasswordEncoder passwordEncoder;
	@Autowired
	private LoginService loginService;
	@Autowired
	private Environment environment;
	@Autowired
	private SecurityService securityService;
	@Autowired
	private QuestionService questionService;
	
	private String login="login";

	@GetMapping(value = "/")
	public ModelAndView gethome(@RequestParam Optional<String> error) {
		return new ModelAndView(login,"","");
	}
	
	@GetMapping(value = "/login")
	public ModelAndView getLoginDetails(@RequestParam Optional<String> error) {
		return new ModelAndView(login,"","");
	}

	@PostMapping(value = "/authenticateLogin")
	public String authenticateLogin(@Valid @ModelAttribute("command") Login userLogin, BindingResult result,
			ModelMap model, SessionStatus status,HttpSession session) {		

		//ModelAndView modelAndView = new ModelAndView("error"); 
		String view = "error";
		status.setComplete();
		
		try {
			if (result.hasErrors()) {
				view="login";
				model.addAttribute("command", userLogin);
				//modelAndView= new ModelAndView(login, "command", userLogin);
			}
			else{
				UserEntity userEntity = loginService.authenticateLogin(userLogin);
				
				securityService.autoLogin(userLogin.getUserName(), userLogin.getPassword());
				
				model.addAttribute("userName", userEntity.getName());
				final int maxResult = 5;
		        final int maxNavigationPage = 10;
		        /*PaginationResult<ProductInfo> productResult = productService.queryProducts(1, 
		                maxResult, maxNavigationPage, "");
		        model.addAttribute("paginationProducts", productResult);*/
		        model.addAttribute("userName", Utils.getloggedInUserName());
		        
		        view="redirect:/listExams";
                //modelAndView = new ModelAndView("listExams");	
			}
		}
		catch (Exception e) {
			if (e.getMessage().contains("LoginService")) {
				view="login";
				model.addAttribute("loginName",  userLogin.getUserName());
				//modelAndView = new ModelAndView(login); 
				//modelAndView.addObject("loginName", userLogin.getUserName());
			}
			//modelAndView.addObject("message", environment.getProperty(e.getMessage()));
			//model.addObject("message", environment.getProperty(e.getMessage()));
		}
		
		return view;
	}
	
	@GetMapping(value = "/logout")
	public ModelAndView logout(HttpSession session) {
		ModelAndView model = new ModelAndView("home", "", "");
		Enumeration<String> attributes = session.getAttributeNames();

		while (attributes.hasMoreElements())
			session.removeAttribute(attributes.nextElement());
		
		model.addObject("logoutMessage", environment.getProperty("LoginController.LOGOUT_SUCCESS"));
		return model;
	}

}

src/main/webapp/WEB-INF/pages/aboutus.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
	<!-- ABOUT US -->
        <div class="row marginbottom-150">
		<div class="container col-sm-offset-1 col-sm-5 col-left ">
			<h1 class="capital">
				<strong>About Us</strong>
			</h1>
			<span class="st-border"></span>
			<div class="about-us ">
				<br>
				<p>
					<b>Why Pariwar Super Shopee?<br></b> Pariwar Super Shopee is a low-price supermarket that allows you to buy products across categories 
					like grocery, vegetables, beauty & wellness, household care, baby care and variety of other products..
				</p>
			</div>
		</div>
	<!-- /ABOUT US -->

src/main/webapp/WEB-INF/pages/awsExamList.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Exam List</title>
<link rel="stylesheet" href="<c:url value='css/parivar.css'/>" type="text/css" media="all">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<!-- HEADER -->
	<fmt:setLocale value="en_IN" scope="session"/>
	<!-- /HEADER -->
	  
	<header id="header">
	<nav class="navbar st-navbar navbar-fixed-top" >
		<div class="container-fluid">
		 <div class="collapse navbar-collapse" id="st-navbar-collapse">
		 <div style="width:95%;margin-left:50px;">
				<ul class="nav navbar-nav navbar-right margintop-5" >
			       	<li class="btn btn-md fontstyle"  style="margin-top:5px;border-top-width:1px;color:SteelBlue"> 
			       	<span class="glyphicon glyphicon-user"></span>Welcome <b>${userName}</b>&nbsp;</li>
			       	<li> <a class="btn btn-md " href="listExams" style="color:green;margin-top:10px;border-top-width:1px">
                      	<span class="glyphicon glyphicon-log-out"></span>&nbsp;Exam List
                	</a> </li>
					<li> <a class="btn btn-md " href="logout" style="color:green;margin-top:10px;border-top-width:1px">
                      	<span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout
                	</a> </li>
				</ul>  
				<ul class="nav navbar-nav nav-links">
				 <a class="logo1"  href="${pageContext.servletContext.contextPath}">
					<img id="a" style="padding:0px 0px;width:200px;vertical-align:top;" src="<c:url value='images/cloud.png'/>"></img> 
				 </a>
			    </ul>
				<hr style="width:100%;height:2px;border-width:1;color:gray;background-color:gray">
		 </div>
		</div>  
	</div>
	</nav>
    </header>
	<!-- /HEADER --><br><br><br>
	   <div class="container col-sm-5 col-right" style="align:center;width:95%;padding:0px 20px;margin-left:40px;height:50%">
	 		<div class="panel panel-default">
		         <div style="color:#f5f5f5;background-color:#337ab7;border-color:#337ab7;padding:25px 5px;width:100%;height:50%">   
		           <span></span>&nbsp;<strong>AWS Exam - (CLFC01) </strong>
				 </div>
			 	 <div style="width:100%;margin-left:30px;margin-top:50px;">
			 	 	<div class="customer-info-container">
						   <table border="1" style="width:95%;font-size:12px;border-color:black">
						       <tr align="center" style="color:#f5f5f5;background-color:#337ab7;border-color:black;">
						           <th style="padding-left:5px">Number</th>
						           <th style="padding-left:25px">Name</th>
						           <th style="padding-left:5px">Total Questions</th>
						           <th style="padding-left:5px">Attended Questions</th>
						           <th style="padding-left:5px">Total Marks</th>
						           <th style="padding-left:5px">Percentage</th>
						           <th style="padding-left:5px">Result</th>
						    	   <th style="padding-left:5px">Action</th>
						       </tr>
						       <c:forEach items="${awsExamList}" var="exam" varStatus="count">
						           <c:set var="bColor" value="#C0C0C0" />
						           <c:if test="${exam.started}">
						       			<c:set var="bColor" value="#ffc252" />
						           </c:if>
						           <tr align="center" style="color:black;background-color:${bColor};border-color:black;">
						           	   <td style="align:center;padding-left:5px"><strong>${count.index+1}</strong></td>
						               <td><strong>${exam.name}</strong></td>
						               <td><strong>50</strong></td>
						               <td><strong>${exam.attended}</strong></td>
						               <td><strong>${exam.totalMarks}</strong></td>
						               <td><strong>${exam.percentage}</strong></td>
						               <td><strong>${exam.result}</strong></td>
						               <td>
						                <c:if test="${exam.started}">
						                	<a class="btn btn-md " href="getQuestions?qStart=${exam.qstart}&qCurrent=${exam.qstart}&qEnd=${exam.qend}&examcode=${exam.code}" 
							               		style="color:green;border-top-width:1px">
						                      	<span class="glyphicon glyphicon-check"></span>&nbsp;<strong>Resume</strong>
					                		</a>
						                </c:if>
					               		<c:if test="${!exam.started}">
					               			<a class="btn btn-md " href="getQuestions?qStart=${exam.qstart}&qCurrent=${exam.qstart}&qEnd=${exam.qend}&examcode=${exam.code}" 
							               		style="color:green;border-top-width:1px">
						                      	<span class="glyphicon glyphicon-check"></span>&nbsp;<strong>Start</strong>
					                		</a>
					               		</c:if>
                					</td>
						           </tr>
						       </c:forEach>
						   </table>
		 			</div>
	  	 		</div>
			</div>
		</div>
<jsp:include page="footer.jsp"></jsp:include>
</body>
</html>

src/main/webapp/WEB-INF/pages/contactus.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
	<!-- FOOTER -->
	<footer id="footer" style="position : fixed ; bottom : 0px; width : 100% ;">
		<div class="container">
			    <div class="row">
				<div class="col-sm-6 col-sm-push-6 footer-social-icons padding-15">
					<span>Follow us:</span>
					<a href=""><img src="<c:url value='images/fb.png'/>"></img></a>
					<a href=""><img src="<c:url value='images/gp.png'/>"></img></a>
					<a href=""><img src="<c:url value='images/yt.png'/>"></img></a>
					<a href=""><img src="<c:url value='images/t.png'/>"></img></a>
				</div>
				<!-- /SOCIAL ICONS -->
				<div class="col-sm-6 col-sm-pull-6 padding-15" >
					<p><COPYRIGHT/> 2017 <a href="${pageContext.servletContext.contextPath}">InfyGo</a>. All Rights Reserved.</p>
				</div>
				</div>
		</div>
	</footer>
	<!-- /FOOTER -->
	

src/main/webapp/WEB-INF/pages/error.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>AWS Exam</title>
<link rel="stylesheet" href="<c:url value='css/parivar.css'/>" type="text/css" media="all">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

   <br><br><br>
		<div class="container  col-right " style="width:40%;float:center;">
			<br> <br> <br>
			${error} 
		</div>
</body>
</html>

src/main/webapp/WEB-INF/pages/failure.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1></h1>
        <br><br>
    <center>
       <!--  <h3>Invalid crendentials!!</h3> -->
       <h3>${command}</h3>
    </center>
</body>
</html>

src/main/webapp/WEB-INF/pages/forgotPassword.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>InfyGo Reservation System</title>

<link rel="stylesheet" href="<c:url value='css/newstyle.css'/>"
type="text/css" media="all">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" 
rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="<c:url value='/resources/css/custom.css'/>" type="text/css" media="all">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<!-- HEADER -->
	<jsp:include page="header.jsp"></jsp:include>
	<!-- /HEADER -->
	<!-- Login start -->
    <!-- ABOUT US -->
    <jsp:include page="aboutus.jsp"></jsp:include>
	<!-- /ABOUT US -->
	
	<div class="container  col-sm-5 col-right " style="width:50%">
			<br> <br> <br>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="capital">Forgot Password</h4>
				</div>
				<div class="panel-body">
					<h3 class="red" id="msg2"></h3>
					<form:form method="POST" action="resetPassword" modelAttribute="command">
					<!-- <h7><font class="control-label col-sm-offset-1 col-sm-3 text-right fontstyle">Email&Phone Provided during registration with InfyGO<span
										class="red">*</span>
								</font></h7> -->
							<div class="form-group">
								<form:label path="email"
									class="control-label col-sm-offset-1 col-sm-3 text-right fontstyle">Email Id<span
										class="red">*</span>
								</form:label>
								<div class="col-sm-7">
									<form:input path="email" class="form-control" />
									<br>
									<form:errors path="email" />
								</div>
								<br>
							</div>
							<div class="form-group">
								<form:label path="phone"
									class="control-label col-sm-offset-1 col-sm-3 text-right fontstyle">Phone Number<span
										class="red">*</span>
								</form:label>
								<div class="col-sm-7">
									<form:input path="phone" class="form-control" />
									<br>
									<form:errors path="phone" />
								</div>
								<br>
							</div>
							<div class="form-group">
								<form:label path="newPassword"
									class="control-label col-sm-offset-1 col-sm-3 text-right fontstyle">New Password<span
										class="red">*</span>
								</form:label>
								<div class="col-sm-7">
									<form:input type="password" path="newPassword"
										class="form-control" />
									<br>
									<form:errors path="newPassword" />
								</div>
								<br>
							</div>
							<br><br><br><br>
							<div class="form-group">
								<div class="col-sm-offset-1">
									<font class="control-label text-right fontstyle">Please enter your Email Id and Phone number for confirmation</font>
								</div>
							</div>
						  <div class="form-group">
								<div class="col-sm-offset-4 col-sm-7">
									<button
										type="submit" class="btn btn-primary fontfamily">Reset Password</button>
								</div>
							</div>
					</form:form>
					<div class="col-md-12 text-center">
                   <div class="text-center text-danger">${message}</div>  
                   </div>
					  <c:if test="${successMessage ne null}">
						<div class="alert alert-success col-md-12" align="center">${successMessage}
						<br>
						Click <a href="login" > &nbsp;here </a>to login.
                  		</div>
					</c:if>
					</div>
				</div>
			</div>
	</div>
	<!-- Login end -->
	<jsp:include page="footer.jsp"></jsp:include>
</body>
</html>

src/main/webapp/WEB-INF/pages/header.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!-- HEADER -->
<header id="header">
	<nav class="navbar st-navbar navbar-fixed-top" >
		 	<div class="collapse navbar-collapse" id="st-navbar-collapse">
			<div  style="width:95%;">
				<ul class="nav navbar-nav navbar-right margintop-5 " >
					<li>  <a class="btn btn-md " href="register" style="margin-top:10px;border-top-width:1px">
                       <span class="glyphicon glyphicon-user"></span>&nbsp;Sign Up
                    </a> </li>
			        <li><a class="btn btn-md  nav-links-right  " href="login" style="margin-top:10px;border-top-width:1px">
                       <span class="glyphicon glyphicon-log-in"></span>&nbsp;Login
                    </a></li> 
                 </ul> 
                 <ul class="nav navbar-nav nav-links">
					 <a class="logo1"  href="${pageContext.servletContext.contextPath}">
						<img id="a" style="padding:0px 0px;width:200px;vertical-align:top;" src="<c:url value='images/pariwar.png'/>"></img> 
					 </a>
				</ul>
				<hr style="width:100%;height:2px;border-width:1;color:gray;background-color:gray">
			</div>
		</div>  
	</nav>
</header>
<br>
<!-- /HEADER -->

src/main/webapp/WEB-INF/pages/questionsList.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Question</title>
<link rel="stylesheet" href="<c:url value='css/parivar.css'/>" type="text/css" media="all">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<!-- HEADER -->
	<fmt:setLocale value="en_IN" scope="session"/>
	<header id="header">
		<nav class="navbar st-navbar navbar-fixed-top">
			<div class="container-fluid" align="center">
				 <div class="collapse navbar-collapse" id="st-navbar-collapse">
				 <div style="width:95%;margin-left:10px;align:center">
						<ul class="nav navbar-nav navbar-right margintop-5" >
							<li class="btn btn-md fontstyle"  style="margin-top:5px;border-top-width:1px;color:SteelBlue"> 
							<span class="glyphicon glyphicon-user"></span>Welcome <b>${userName}</b>&nbsp;</li>
							<li> <a class="btn btn-md " href="listExams" style="color:green;margin-top:10px;border-top-width:1px">
								<span class="glyphicon glyphicon-log-out"></span>&nbsp;Exam List
							</a> </li>
							<li> <a class="btn btn-md " href="logout" style="color:green;margin-top:10px;border-top-width:1px">
								<span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout
							</a> </li>
						</ul>  
						<ul class="nav navbar-nav nav-links">
						 <a class="logo1"  href="${pageContext.servletContext.contextPath}">
							<img id="a" style="padding:0px 0px;width:200px;height:100px;vertical-align:top;" src="<c:url value='images/cloud.png'/>"></img> 
						 </a>
						</ul>
						<hr style="width:100%;height:2px;border-width:1;color:gray;background-color:gray"/>
				 </div>
				</div>  
			</div>
		</nav>
    </header>
	<!-- /HEADER -->
	  <div class="container col-sm-5 col-right" align="left" style="width:95%;height:100%;margin-top:150px;margin-left:45px;">
	 		<div class="panel panel-default">
		         <div style="color:#f5f5f5;background-color:#337ab7;border-color:#337ab7;">   
		           <span></span>&nbsp;<strong>AWS Exam - (CLFC01) </strong>
				 </div>
				 <div style="color:#f5f5f5;background-color:white;border-color:#337ab7;margin-top:15px;margin-left:25px;">   
		           <c:if test="${paginationQuestionResult.totalPages > 1}">
				            <c:forEach begin="${startQues}" end="${endQues}" var="index">
				               <c:set var="qstatus" value="false" />
				               <c:if test="${qList!=null}">
				                   <c:if test="${qList.get(String.valueOf(index)) !=null}">
				                      <c:if test="${qList.get(String.valueOf(index)).selOptionsList.size()>0}">
				                         <c:set var="qstatus" value="true" />
				                      </c:if> 
				                   </c:if> 
				               </c:if>
				               <c:if test="${qstatus}">
				                  <c:if test="${qList.get(String.valueOf(index)).isMatched()}">
				                      <a href="#" class="nav-item" onclick="onQuestionClick(${index})">
										<label style="color:#f5f5f5;width:40px;background-color:green; border-top :solid 3px transparent"><strong>${index}</strong></label>
									  </a>
				                  </c:if>
				                  <c:if test="${!qList.get(String.valueOf(index)).isMatched()}">
				                     <a href="#" class="nav-item" onclick="onQuestionClick(${index})">
										<label style="color:#f5f5f5;width:40px;background-color:brown; border-top :solid 3px transparent"><strong>${index}</strong></label>
									  </a>
				                  </c:if>
				               </c:if>
				               <c:if test="${!qstatus}">
				                 <a href="#" class="nav-item" onclick="onQuestionClick(${index})">
									<label style="color:#f5f5f5;width:40px;background-color:#337ab7; border-top :solid 3px transparent"><strong>${index}</strong></label>
								  </a>
				               </c:if>
							</c:forEach>
					</c:if>
				 </div>
			 	 <div style="width:95%;margin-top:15px;margin-left:25px;">
			 	 	    <form:form method="POST" id="questionForm" modelAttribute="questionForm" action="${pageContext.request.contextPath}/listQuestion">
						   <table border="1" style="width:100%;font-size:14px;border-color:black">
						       <tr style="color:#f5f5f5;background-color:#337ab7;border-color:#337ab7;padding: 0px 0px;">
						           <th style="padding: 5px 15px;">Number</th>
						           <th style="padding: 5px 15px;">Question</th>
						       </tr>
						       <input type="textbox" hidden='true' id="qStart" name="qStart" value='${startQues}'/>
						       <input type="textbox" hidden='true' id="qEnd" name="qEnd" value='${endQues}'/>
						       <c:forEach items="${paginationQuestionResult.list}" var="questionInfo">
						           <tr style="padding: 5px ">
						               <td style="padding: 5px 15px;width:5%;">${questionInfo.queNumber}
						               <input type="textbox" hidden='true' id="quenumber" name="quenumber" value='${questionInfo.queNumber}'/>
						               <input type="textbox" hidden='true' id="queAns" name="queAns" value='${questionInfo.ans}'/>
						               </td>
						               <td style="padding: 5px 15px;width:95%;">${questionInfo.que}
						               <a href="#" title="${questionInfo.ans}" style="color:#00CC00;"><span class="glyphicon glyphicon-flag"></span>&nbsp;</a></a>
						               <a href="#" title="${questionInfo.notes}" style="color:#00CC00;"><span class="glyphicon glyphicon-flag"></span>&nbsp;</a></a>
						               </td>
						           </tr>
						           <c:forEach items="${questionInfo.options}" var="options">
							           <tr style="padding: 5px 15px;">
							               <td style="padding: 5px 15px;width:10%;">
							               <input type="checkbox" id="quesOptions" ${options.checked} name="quesOptions" value='${options.code}'/>
							               ${options.code}</td>
							               <td style="padding: 5px 15px;width:80%;">${options.optionTxt}</td>
							           </tr>
						       	   </c:forEach>
						       </c:forEach>
						   </table>
						   <br>
						    <c:if test="${paginationQuestionResult.totalPages > 1}">
						       <div class="page-navigator" >
						          <a href="#" onClick="onQuestionFormSubmit(${paginationQuestionResult.getCurrentPage()+1})" class="nav-item">
				                  <span class="glyphicon glyphicon-hand-right"></span>&nbsp;<strong>Next</strong></a> 
				                  </a>&nbsp;
				                  <a href="#" onClick="onQuestionFormSubmit(${paginationQuestionResult.getCurrentPage()-1})" class="nav-item">
						           <span  class="glyphicon glyphicon-hand-left"></span>&nbsp;<strong>Back</strong></a>
						          </a>&nbsp;
						          <a href="#" onClick="saveExam(${paginationQuestionResult.getCurrentPage()-1})" class="nav-item">
						           <span class="glyphicon glyphicon-save"></span>&nbsp;<strong>Save</strong></a>
						          </a>&nbsp;
						           <a href="#" onClick="saveExam(${paginationQuestionResult.getCurrentPage()-1})" class="nav-item">
						           <span class="glyphicon glyphicon-save"></span>&nbsp;<strong>Submit</strong></a>
						          </a>
						       </div>
						   </c:if>
						</form:form>   
	  	 		</div>
			</div>
		</div>
<script>
  function onQuestionFormSubmit(currentQues){
	  var questionForm = document.getElementById('questionForm');
	  questionForm.action='navigateQuestion?qCurrent='+currentQues;
	  questionForm.submit();
  }
  function saveExam(currentQues){
	  var questionForm = document.getElementById('questionForm');
	  questionForm.action='saveExam?qCurrent='+currentQues;
	  questionForm.submit();
  }
  function onQuestionClick(currentQues){
	  var questionForm = document.getElementById('questionForm');
	  questionForm.action='navigateQuestion?qCurrent='+currentQues;
	  questionForm.submit();
  }
</script>
</body>
</html>